helloidol/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('playground/', include('playground.urls')),
    path('txt/', include('txt.urls')),
    # path('playground/hello/', playgound.views.say_hello, name='playground_hello'),
    # path('playground/hello_html/', playgound.views.say_hello_html, name='playground_hello_html'),
    path('admin/', admin.site.urls),
]

playground/urls.py
from django.urls import path

from playground import views

app_name='playground'

urlpatterns =[
    path('hello/', views.say_hello, name='hello'), #{% url 'playground:hello'%}
    path('hello_html/', views.say_hello_html, name='hello_html'), #{% url 'playground:hello_html'%}
    path('bye_html/', views.bye_html, name='bye_html')
]

txt/urls.py
from django.urls import path

from txt import views

app_name='txt'

urlpatterns=[
    path('멤버리스트/', views.show_멤버리스트, name='멤버리스트'),
    path('<멤버>/', views.show_멤버, name='멤버'),
    # path('subin/', views.show_, name='subin'),
    # path('yeonjun/', views.show_yeonjun, name='yeonjun'),
    # path('teahyeon/', views.show_teahyeon, name='teahyeon'),
    # path('huning/', views.show_huning, name='huning'),
    # path('bumgue/', views.show_bumgue, name='bumgue'),
]

playground/models.py
from django.db import models

# Create your models here.

playgound/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def say_hello(request):
    return HttpResponse("Hello World")

def say_hello_html(request):
    return render(request, 'playground/hello.html', {'name':'야','greeting':'hi'})

def bye_html(request):
    context = {
        'singer':'박재정',
        'title':'헤어지자 말해요'
    }
    return render(request, 'playground/bye.html',context=context)

playground/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def say_hello(request):
    return HttpResponse("Hello World")

def say_hello_html(request):
    return render(request, 'playground/hello.html', {'name': '야', 'greeting': 'hi'})

def bye_html(request):
    context = {
        'singer':'박재정',
        'title':'헤어지자 말해요'
    }
    return render(request, 'playground/bye.html', context=context)

playground/templates/playground/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bye</title>
</head>
<body>
<h2>{{ title }} - {{ singer }}</h2><br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/SrQzxD8UFdM" title="헤어지자말해요 - 박재정" frameborder="0"
        allow="accelerometer;" allowfullscreen></iframe>
<pre>
        헤어지자고 말하려 오늘
너에게 가다가 우리 추억 생각해 봤어
처음 본 네 얼굴 mm
마주친 눈동자 ooh-whoa
가까스로 본 너의 그 미소들
손을 잡고 늘 걷던 거리에
첫눈을 보다가 문득 고백했던 그 순간
가보고 싶었던 식당
난생처음 준비한 선물
고맙다는 너의 그 눈물들이
바뀔까 봐 두려워
그대 먼저 헤어지자 말해요
나는 사실 그대에게 좋은 사람이 아녜요
그대 이제 날 떠난다 말해요
잠시라도 이 행복을 느껴서 고마웠다고
시간이 지나고 나면 나는
어쩔 수 없을 걸 문득 너의 사진 보겠지
새로 사귄 친구 함께
웃음 띤 네 얼굴 보면
말할 수 없을 묘한 감정들이
힘들단 걸 알지만
그대 먼저 헤어지자 말해요
나는 사실 그대에게 좋은 사람이 아녜요
그대 이제 날 떠난다 말해요
잠시라도 이 행복을 느껴서 고마웠다고 ooh-whoa
한 번은 널 볼 수 있을까?
이기적인 거 나도 잘 알아
그땐 그럴 수밖에 없던 어린 내게
한 번만 더 기회를 주길
그댈 정말 사랑했다 말해요
나는 사실 그대에게
좋은 사람이 되고 싶었어
영영 다신 못 본다 해도
그댈 위한 이 노래가
당신을 영원히 사랑할 테니
    </pre>
</body>
</html>

playground/templates/playground/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello World</title>
</head>
<body>
    <B>Hello World!</B>
    {{ name }},{{ greeting }}
{# {% 파이썬 문법 %} #}
{# {{ 값 출력 }} #}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block css %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

</body>
</html>

txt/templates/txt/bumgue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>투바투 - 범규</title>
    <style>
        img{
            border-radius: 50%;
            width: 300px;
            height: 300px;
        }
    </style>
</head>
<body>
    <h1> 투바투 </h1>
    <h2> 범규 </h2>
    <img src="/투바투/images/qjarb.png">
</body>
</html>

txt/templates/txt/huning.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>투바투 - 휴닝</title>
    <style>
        img{
            border-radius: 50%;
            width: 300px;
            height: 300px;
        }
    </style>
</head>
<body>
    <h1> 투바투 </h1>
    <h2> 휴닝카이 </h2>
    <img src="/투바투/images/gbsldzkdl.png">
</body>
</html>

txt/templates/txt/subin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>투바투 - 수빈</title>
</head>
<body>
    <h1> 투바투 </h1>
    <h2> 수빈 </h2>
    <img src="/투바투/images/chltnqls14.png" alt="" style="border-radius: 50%">
</body>
</html>

txt/templates/txt/teahyeon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>투바투 - 태현</title>
    <style>
        img{
            border-radius: 50%;
            width: 300px;
            height: 300px;
        }
    </style>
</head>
<body>
    <h1> 투바투 </h1>
    <h2> 태현 </h2>
    <img src="/투바투/images/xogus.png"
</body>
</html>

txt/templates/txt/yeonjun.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>투바투 - 연준</title>
    <style>
        img{
            border-radius: 50%;
            width: 300px;
            height: 300px;
        }
    </style>
</head>
<body>
    <h1> 투바투 </h1>
    <h2> 연준 </h2>
    <img src="/투바투/images/duswns.png">
</body>
</html>

txt/templates/txt/멤버.html
{% extends 'base.html' %}

{% block title %}{{ group_name }} - {{ name }}{% endblock %}

{% block content %}
    <a href="{% url 'txt:멤버리스트' %}"><h2>❤멤버리스트</h2></a>
    <title>{{ group_name }} - {{ name }}</title>

    <h1> {{ group_name }} </h1>
    <h2> {{ name }} </h2>
    {% load static %}
    <img src="{% static img_src %}" alt="" style="border-radius: 100%; width: 800px">
{% endblock %}

txt/templates/txt/멤버리스트.html
{% extends 'base.html' %}

{% block title %}투바투 - 멤버리스트{% endblock %}

{% block content %}
<table class="table">
    <tr>
        <th>이름 http://localhost</th>
        <th>이름 ../../</th>
        <th>이름/</th>
        <th>txt django</th>
    </tr>
    {# members에서 하나씩 꺼내어 member에 넣자 #}
    {% for member in members %}
        <tr>
            {# 멤버이름에 링크 : txt/{{member.name}} #}
    	<td><a href="http://localhost:8000/txt/{{ member.name }}/">{{ member.name }}</a> //: 인터넷 절대</td>
            <td><a href="../../txt/{{ member.name }}/">{{ member.name }}</a> ../../: 부모/부모/ 주소(상대) </td>
            <td><a href="/txt/">{{ member.name }}</a> /: 호스트 루트(호스트 절대)</td>
            <td><a href="{% url 'txt:멤버' 멤버=member.name %}">{{ member.name }}</a> </td>
            {% load static %}
        <td><img src="{% static member.img_src %}" alt="" style="height: 300px; border-radius: 100%"></td>
        </tr>
    {% endfor %}


</table>
{% endblock %}